const express=require('express')
const services_Booking=require('../services/Booking.services')
const route=express.Router()
const alowedto=require('../middleware/alowedTo')
const {add_Booking_schema,update_Booking_schema}=require('../validation/validtoin.Bookings')
const validate=require('../middleware/validate')
const verifyToken=require('../middleware/vreifyToken')
route.get('/',verifyToken,alowedto('admin'),services_Booking.get_all_Booking)
route.get('/get/:id_Booking',verifyToken,alowedto('admin'),services_Booking.get_Booking)
route.post('/add',validate(add_Booking_schema),verifyToken,services_Booking.add_Booking)
route.patch('/update/:id_Booking',validate(update_Booking_schema),verifyToken,alowedto('admin'),services_Booking.update_Booking)
route.delete('/delete/:id_Booking',verifyToken,alowedto('admin'),services_Booking.delete_Booking)
module.exports=route