const express=require('express')
const route=express.Router()
const services_lesson=require('../services/lessons.services')
const alowedto=require('../middleware/alowedTo')
const {add_lesson_schema,update_lesson_schema}=require('../validation/validtion.lessons')
const validate=require('../middleware/validate')
const verifyToken=require('../middleware/vreifyToken')
route.post('/add',validate(add_lesson_schema),verifyToken,alowedto('instructor', 'admin'),services_lesson.add_lesson)
route.delete('/delete/:id_lesson',verifyToken,alowedto('instructor', 'admin'),services_lesson.delete_lesson)
route.patch('/update/:id_lesson',validate(update_lesson_schema),verifyToken,alowedto('instructor', 'admin'),services_lesson.update_lesson)
module.exports=route